version: '3.10'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/home/manuel/volumes/postgres
    environment:
      - POSTGRES_PASSWORD=gameDock
  web:
    image: gamedock.azurecr.io/gamedocke-web:2.0
    ports:
      - "8080:8080"
    volumes:
      - /home/manuel/volumes/gamedock
    depends_on:
      - db

volumes:
  postgres_data:
