from python:3.10-alpine

RUN apk add --no-cache git 

WORKDIR /app

RUN pip install --upgrade pip

RUN git clone https://github.com/Mancabm/gameDock.git .
RUN pip install -r requirements.txt

ADD docker_settings.py /app/GameDock/settings.py

COPY .env GameDock/.env

CMD ash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata initial_data.json && python3 manage.py runserver 0.0.0.0:8080"